version: '3'

services:
  mongo:
    image: "mongo:3-stretch"
    ports:
      - "27017:27017"
    networks:
      - hackernews-network
  
  mongo-express:
    image: "mongo-express:latest"
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - hackernews-network

networks:
  hackernews-network:
    external: false
